### ISSUE TITLE
Don't create scene object for sensor data not asked for

### ISSUE THREAD

**Issue by adybbroe** [pytroll/trollflow2#21]
It should be possible to allow passing a set of allowed sensors so that scene creation can will be done only when for the data that match one of these sensors:

In the PR#20 @pnuu wrote:

> What happens if there's a reader for the received files, but data are not what actually is meant to be processed? From Slack the original issue was getting wrong instrument data from AAPP, so in my opinion it would be better to configure the actual sensor(s) and check the incoming data against that list. Actually that could be just an addition to the current version, which is a good check to make.

**Comment by pnuu** [comment]
This was closed by #73
