### ISSUE TITLE
Document Trollflow production chain - Meteosat

### ISSUE THREAD

**Issue by adybbroe** [pytroll/trollflow2#36]
There is a general need for documentation, but let's begin by documenting an example production chain with SEVIRI!

**Comment by pnuu** [comment]
Three example configurations (SEVIRI, EARS/AVHHR, EARS/VIIRS) for *full* production chains are available  in `examples/docker/`. It was discussed during PCW that after https://github.com/pytroll/trollflow-sat/issues/36 is completed it will be adjusted also for `trollflow2`.

**Comment by djhoese** [comment]
@pnuu This issue was transferred by me from the trollflow-sat repository to the trollflow2 repository. So this is now the same issue as the one you've linked to.

**Comment by pnuu** [comment]
The example chains have already been documented as a docker examples. The same configurations can be used as a starting point for non-docker chains.
